### ISSUE TITLE
Unable to handshake with id.twitch.tv

### ISSUE THREAD

**Issue by kristoff-it** [alexnask/iguanaTLS#3]
Hi, iguanaTLS works perfectly well when getting emotes, but I get a handshake error when trying to connect to Twitch's token validation endpoint.

To test you can just send a GET request to https://id.twitch.tv/oauth2/validate, it should return a nice json response with an error code in it.

**Comment by alexnask** [comment]
Thanks, I will check this out first thing tomorrow

**Comment by kristoff-it** [comment]
🙏
